# Lab_02

In [47]:
# Importing Necessary Libraries
import numpy as np
import pandas as pd

In [49]:
# printing the Data of IRIS Dataset
Filename = 'Iris.csv'
Data = pd.read_csv(Filename)
print(type(Data))
Data

<class 'pandas.core.frame.DataFrame'>


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [37]:
cols = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
Data_Matrix = Data.get(cols).to_numpy()

## Making Data Matrix

In [46]:
print(Data_Matrix.shape)
print(Data_Matrix)
print(type(Data_Matrix))

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

## Attributes

In [59]:
features = (list(Data.columns))[1:5]
features

['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

## Mean

In [85]:
Mean_List = []
for j in range(4):
    Sum = 0
    for i in range(150):
        Sum = Sum + Data_Matrix[i][j]
    mean = Sum/150
    Mean_List.append(round(mean, 2))
Mean_List = np.array(Mean_List)
print(Mean_List)

[5.84 3.05 3.76 1.2 ]


## Variance

In [86]:
Variance_List = []
for j in range(4):
    Sum = 0
    for i in range(150):
        Sum = Sum + (Data_Matrix[i][j] - Mean_List[j])**2
    var = Sum/150
    Variance_List.append(round(var, 2))

In [93]:
Variance_List = np.array(Variance_List)
print(Variance_List)

[0.68 0.19 3.09 0.58]


## Covariance

In [110]:
# Covariance between Sepal_Length and Sepal_Width
Cov = []
Sum = 0
for i in range(150):
    Sum = Sum + (Data_Matrix[i][0]-Mean_List[0])*(Data_Matrix[i][1]-Mean_List[1])
Covar = round(Sum/150, 3)
Cov.append(Covar)
Sum = 0
for i in range(150):
    Sum = Sum + (Data_Matrix[i][2]-Mean_List[2])*(Data_Matrix[i][3]-Mean_List[3])
Covar = round(Sum/150, 3)
Cov.append(Covar)
np.array(Cov)
print(Cov)

[-0.039, 1.288]


## Correlation

In [121]:
Cor1 = round(Cov[0]/((Variance_List[0]**0.5)*(Variance_List[1]**0.5)), 3)
Cor2 = round(Cov[1]/((Variance_List[2]**0.5)*(Variance_List[3]**0.5)), 3)

In [122]:
Correlation = []
Correlation.append(Cor1)
Correlation.append(Cor2)

In [123]:
np.array(Correlation)
print(Correlation)

[-0.109, 0.962]
